all:
  children:
    proxmox:
      hosts:
        predatorx:
          ansible_connection: local
          backtesting_vm_id: 100
          ml_vm_id: 101
          webserver_vm_id: 102
          db_container_id: 200
          backup_container_id: 201