---
all:
  children:
    proxmox:
      hosts:
        predatorx:
          ansible_connection: local
          backtesting_vm_id: 100
          ml_vm_id: 101
          webserver_vm_id: 102
          db_container_id: 200
          backup_container_id: 201
          proxmox_host: "192.168.1.100" # Remplacez par l'IP de votre serveur Proxmox
          proxmox_user: "root@pam" # Remplacez par votre utilisateur Proxmox
          proxmox_password: "your_proxmox_password" # Remplacez par votre mot de passe Proxmox
          proxmox_target: "pve" # Remplacez par le nom de votre nœud Proxmox
          bridge_interface: vmbr0 # Remplacez par votre interface réseau de pont
      vars:
        vm_memory: 4096 # Exemple de mémoire
        vm_cores: 4 # Exemple de nombre de cœurs
        vm_disk_size: "60G" # Exemple de taille de disque
        vm_iso_image: "local:iso/ubuntu-22.04.3-live-server-amd64.iso" # Exemple d'image ISO
        backtesting_gpu_indices: [0] # Exemple d'index de GPU
        start_vm_after_creation: true # Exemple pour démarrer la vm après creation.

backtesting:
  hosts:
    predatorx:
      vm_id: "{{ hostvars['predatorx']['backtesting_vm_id'] }}"