---
# Playbook principal pour la configuration de l'environnement MLENV
# À exécuter avec: ansible-playbook -i inventory/hosts.yml playbooks/site.yml

- name: Configuration de Proxmox
  hosts: proxmox
  gather_facts: true
  tags:
    - proxmox
    - setup
  tasks:
    - name: Inclure le playbook de configuration Proxmox
      include_tasks: proxmox-setup.yml

- name: Création des VMs Backtesting
  import_playbook: backtesting-vm.yml
  tags:
    - vms
    - backtesting

- name: Création des VMs Machine Learning
  import_playbook: ml-vm.yml
  tags:
    - vms
    - ml

- name: Création et configuration des conteneurs LXC
  import_playbook: container-setup.yml
  tags:
    - containers

- name: Création de la VM de serveur web (optionnel)
  import_playbook: web-vm.yml
  tags:
    - vms
    - webserver
  when: create_web_server | default(false) | bool

- name: Configuration de l'environnement Backtesting
  hosts: backtesting
  gather_facts: true
  tags:
    - vm-setup
    - backtesting
  vars:
    vm_user: "{{ backtesting_user }}"
  tasks:
    - name: Inclure le playbook de configuration de la VM de backtesting
      include_tasks: backtesting-vm-setup.yml
      when: configure_vm_environments | default(false) | bool

- name: Configuration de l'environnement Machine Learning
  hosts: machine_learning
  gather_facts: true
  tags:
    - vm-setup
    - ml
  vars:
    vm_user: "{{ ml_user }}"
  tasks:
    - name: Inclure le playbook de configuration de la VM de machine learning
      include_tasks: ml-vm-setup.yml
      when: configure_vm_environments | default(false) | bool

- name: Configuration des sauvegardes et maintenance
  hosts: proxmox
  gather_facts: true
  tags:
    - maintenance
  tasks:
    - name: Vérifier si le script de sauvegarde existe
      stat:
        path: /usr/local/bin/pve-backup.sh
      register: backup_script

    - name: Copier le script de sauvegarde
      template:
        src: ../templates/pve-backup.sh.j2
        dest: /usr/local/bin/pve-backup.sh
        mode: '0755'
      when: not backup_script.stat.exists

    - name: Configurer la tâche cron pour les sauvegardes
      cron:
        name: "Sauvegardes Proxmox quotidiennes"
        hour: "1"
        minute: "0"
        job: "/usr/local/bin/pve-backup.sh > /var/log/pve-backup/backup-$(date +\\%Y-\\%m-\\%d).log 2>&1"